export interface PlanetaryFact {
  day: number;
  fact: string;
}

export interface PlanetFacts {
  [key: string]: PlanetaryFact[];
}

export const planetaryFacts: PlanetFacts = {
  sun: [
    { day: 1, fact: "The Sun contains 99.86% of the mass in our solar system." },
    { day: 2, fact: "The Sun's core temperature reaches about 15 million degrees Celsius." },
    { day: 3, fact: "Every second, the Sun converts 600 million tons of hydrogen into helium." },
    { day: 4, fact: "The Sun is about 4.6 billion years old and is considered middle-aged." },
    { day: 5, fact: "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth." },
    { day: 6, fact: "The Sun rotates faster at its equator than at its poles." },
    { day: 7, fact: "Solar flares can release energy equivalent to billions of hydrogen bombs." },
    { day: 8, fact: "The Sun's magnetic field is about twice as strong as Earth's." },
    { day: 9, fact: "One million Earths could fit inside the Sun." },
    { day: 10, fact: "The Sun generates energy through nuclear fusion in its core." },
    { day: 11, fact: "The Sun's surface temperature is about 5,500 degrees Celsius." },
    { day: 12, fact: "Solar wind travels at speeds of 400-800 kilometers per second." },
    { day: 13, fact: "The Sun loses about 4 million tons of mass every second." },
    { day: 14, fact: "Sunspots are cooler areas on the Sun's surface caused by magnetic activity." },
    { day: 15, fact: "The Sun will become a red giant in about 5 billion years." },
    { day: 16, fact: "The Sun's gravity is 28 times stronger than Earth's gravity." },
    { day: 17, fact: "The Sun emits energy in all directions, but Earth receives only one billionth of it." },
    { day: 18, fact: "Solar prominences can extend hundreds of thousands of kilometers into space." },
    { day: 19, fact: "The Sun's corona is much hotter than its surface, reaching millions of degrees." },
    { day: 20, fact: "The Sun completes one rotation every 25-35 days, depending on latitude." },
    { day: 21, fact: "Ancient civilizations often worshipped the Sun as a deity." },
    { day: 22, fact: "The Sun produces enough energy every second to power human civilization for 500,000 years." },
    { day: 23, fact: "Solar eclipses occur when the Moon passes between Earth and the Sun." },
    { day: 24, fact: "The Sun's heliopause marks the boundary of our solar system." },
    { day: 25, fact: "The Sun is classified as a G-type main-sequence star." },
    { day: 26, fact: "The Sun's chromosphere gives it a reddish color during eclipses." },
    { day: 27, fact: "Solar neutrinos pass through Earth and your body by the trillions every second." },
    { day: 28, fact: "The Sun's diameter is about 109 times larger than Earth's." },
    { day: 29, fact: "The Sun influences weather patterns and climate on all planets in our solar system." },
    { day: 30, fact: "The Sun will eventually exhaust its hydrogen fuel and become a white dwarf." },
    { day: 31, fact: "The Sun's magnetic field reverses polarity approximately every 11 years." }
  ],
  mercury: [
    { day: 1, fact: "Mercury is the smallest planet in our solar system." },
    { day: 2, fact: "A day on Mercury lasts 59 Earth days." },
    { day: 3, fact: "Mercury has no atmosphere to trap heat, causing extreme temperature variations." },
    { day: 4, fact: "Mercury's surface is covered with craters, similar to our Moon." },
    { day: 5, fact: "Mercury orbits the Sun in just 88 Earth days." },
    { day: 6, fact: "Mercury has a large iron core that makes up about 75% of its radius." },
    { day: 7, fact: "Mercury experiences the greatest temperature variation of any planet." },
    { day: 8, fact: "Mercury has water ice in permanently shadowed craters at its poles." },
    { day: 9, fact: "Mercury has no moons or rings." },
    { day: 10, fact: "Mercury is the second densest planet in our solar system." },
    { day: 11, fact: "Mercury's surface gravity is about 38% of Earth's." },
    { day: 12, fact: "Mercury can reach temperatures of 427°C during the day." },
    { day: 13, fact: "Mercury can drop to temperatures of -173°C at night." },
    { day: 14, fact: "Mercury has a very thin exosphere made of oxygen, sodium, and hydrogen." },
    { day: 15, fact: "Mercury's orbit is the most elliptical of all planets." },
    { day: 16, fact: "Mercury has been visited by only two spacecraft: Mariner 10 and MESSENGER." },
    { day: 17, fact: "Mercury's core is partially molten and generates a weak magnetic field." },
    { day: 18, fact: "Mercury appears to wobble as it orbits due to its elliptical path." },
    { day: 19, fact: "Mercury's surface features include scarps, ridges, and plains." },
    { day: 20, fact: "Mercury is named after the Roman messenger god." },
    { day: 21, fact: "Mercury can be seen from Earth with the naked eye during twilight." },
    { day: 22, fact: "Mercury's largest crater, Caloris Basin, is about 1,550 km in diameter." },
    { day: 23, fact: "Mercury has no seasonal changes due to its minimal axial tilt." },
    { day: 24, fact: "Mercury's magnetic field is about 1% as strong as Earth's." },
    { day: 25, fact: "Mercury completes three rotations for every two orbits around the Sun." },
    { day: 26, fact: "Mercury's surface is made primarily of silicate rock and metal." },
    { day: 27, fact: "Mercury experiences tidal forces from the Sun that have slowed its rotation." },
    { day: 28, fact: "Mercury's thin atmosphere is constantly being replenished by solar wind." },
    { day: 29, fact: "Mercury has the most eccentric orbit of all planets, varying from 46 to 70 million km from the Sun." },
    { day: 30, fact: "Mercury's surface shows evidence of ancient volcanic activity." },
    { day: 31, fact: "Mercury's day-night cycle creates some of the most extreme conditions in the solar system." }
  ],
  venus: [
    { day: 1, fact: "Venus is the hottest planet in our solar system." },
    { day: 2, fact: "Venus rotates backwards compared to most planets." },
    { day: 3, fact: "A day on Venus is longer than its year." },
    { day: 4, fact: "Venus has a thick atmosphere composed mainly of carbon dioxide." },
    { day: 5, fact: "Venus is often called Earth's twin due to similar size." },
    { day: 6, fact: "Venus has surface pressure 90 times greater than Earth's." },
    { day: 7, fact: "Venus is covered by thick clouds of sulfuric acid." },
    { day: 8, fact: "Venus has surface temperatures around 462°C." },
    { day: 9, fact: "Venus has no moons or rings." },
    { day: 10, fact: "Venus is the brightest natural object in the night sky after the Moon." },
    { day: 11, fact: "Venus experiences a runaway greenhouse effect." },
    { day: 12, fact: "Venus has over 1,000 volcanoes on its surface." },
    { day: 13, fact: "Venus rotates once every 243 Earth days." },
    { day: 14, fact: "Venus orbits the Sun in 225 Earth days." },
    { day: 15, fact: "Venus has been visited by more spacecraft than any other planet." },
    { day: 16, fact: "Venus has no global magnetic field." },
    { day: 17, fact: "Venus is named after the Roman goddess of love and beauty." },
    { day: 18, fact: "Venus shows phases like the Moon when viewed from Earth." },
    { day: 19, fact: "Venus has mountains, valleys, and vast plains." },
    { day: 20, fact: "Venus's atmosphere is so thick it would crush a human instantly." },
    { day: 21, fact: "Venus has winds that reach up to 360 km/h in its upper atmosphere." },
    { day: 22, fact: "Venus's surface is hidden beneath its thick cloud cover." },
    { day: 23, fact: "Venus has impact craters that are relatively young." },
    { day: 24, fact: "Venus may have had oceans billions of years ago." },
    { day: 25, fact: "Venus's retrograde rotation may be due to a massive ancient collision." },
    { day: 26, fact: "Venus transits across the Sun's face approximately every 120 years." },
    { day: 27, fact: "Venus has the most circular orbit of all planets." },
    { day: 28, fact: "Venus's thick atmosphere creates a strong greenhouse effect." },
    { day: 29, fact: "Venus's surface features include shield volcanoes and impact craters." },
    { day: 30, fact: "Venus is sometimes called the Morning Star or Evening Star." },
    { day: 31, fact: "Venus has a very slow rotation period, making its day longer than its year." }
  ],
  earth: [
    { day: 1, fact: "Earth is the only known planet with life." },
    { day: 2, fact: "Earth's surface is 71% water." },
    { day: 3, fact: "Earth has one natural satellite, the Moon." },
    { day: 4, fact: "Earth's atmosphere is 78% nitrogen and 21% oxygen." },
    { day: 5, fact: "Earth is about 4.54 billion years old." },
    { day: 6, fact: "Earth's magnetic field protects us from harmful solar radiation." },
    { day: 7, fact: "Earth is the densest planet in our solar system." },
    { day: 8, fact: "Earth's day is exactly 24 hours long." },
    { day: 9, fact: "Earth orbits the Sun at an average speed of 107,000 km/h." },
    { day: 10, fact: "Earth's core is made primarily of iron and nickel." },
    { day: 11, fact: "Earth has plate tectonics that constantly reshape its surface." },
    { day: 12, fact: "Earth's atmosphere extends up to 10,000 km above the surface." },
    { day: 13, fact: "Earth experiences seasons due to its 23.5-degree axial tilt." },
    { day: 14, fact: "Earth's largest ocean is the Pacific, covering about one-third of the planet." },
    { day: 15, fact: "Earth's highest point is Mount Everest at 8,848 meters." },
    { day: 16, fact: "Earth's deepest point is the Mariana Trench at 11,034 meters deep." },
    { day: 17, fact: "Earth's moon is gradually moving away from Earth at 3.8 cm per year." },
    { day: 18, fact: "Earth completes one rotation every 23 hours, 56 minutes, and 4 seconds." },
    { day: 19, fact: "Earth's gravity acceleration is 9.8 meters per second squared." },
    { day: 20, fact: "Earth has a molten outer core that generates its magnetic field." },
    { day: 21, fact: "Earth's biosphere extends from deep in the Earth to several kilometers into the atmosphere." },
    { day: 22, fact: "Earth is located in the habitable zone around the Sun." },
    { day: 23, fact: "Earth's crust is the thinnest layer, averaging about 30-50 km thick." },
    { day: 24, fact: "Earth has over 8.7 million species of life." },
    { day: 25, fact: "Earth's ozone layer protects life from harmful ultraviolet radiation." },
    { day: 26, fact: "Earth's water cycle drives weather patterns and climate." },
    { day: 27, fact: "Earth has experienced five major mass extinction events." },
    { day: 28, fact: "Earth's continents are constantly moving due to plate tectonics." },
    { day: 29, fact: "Earth's auroras are caused by solar particles interacting with the magnetic field." },
    { day: 30, fact: "Earth's diameter is approximately 12,742 kilometers." },
    { day: 31, fact: "Earth is the third planet from the Sun in our solar system." }
  ],
  mars: [
    { day: 1, fact: "Mars is known as the Red Planet due to iron oxide on its surface." },
    { day: 2, fact: "Mars has two small moons: Phobos and Deimos." },
    { day: 3, fact: "A day on Mars is 24 hours and 37 minutes." },
    { day: 4, fact: "Mars has the largest volcano in the solar system, Olympus Mons." },
    { day: 5, fact: "Mars has seasons similar to Earth due to its axial tilt." },
    { day: 6, fact: "Mars has a thin atmosphere composed mostly of carbon dioxide." },
    { day: 7, fact: "Mars has polar ice caps made of water and carbon dioxide." },
    { day: 8, fact: "Mars has the largest canyon in the solar system, Valles Marineris." },
    { day: 9, fact: "Mars takes 687 Earth days to orbit the Sun." },
    { day: 10, fact: "Mars has dust storms that can cover the entire planet." },
    { day: 11, fact: "Mars surface gravity is about 38% of Earth's." },
    { day: 12, fact: "Mars has evidence of ancient riverbeds and lake beds." },
    { day: 13, fact: "Mars has a very weak magnetic field." },
    { day: 14, fact: "Mars temperatures can range from -87°C to -5°C." },
    { day: 15, fact: "Mars has been explored by numerous robotic missions." },
    { day: 16, fact: "Mars has water ice at its poles and possibly underground." },
    { day: 17, fact: "Mars is named after the Roman god of war." },
    { day: 18, fact: "Mars has impact craters from asteroid and comet collisions." },
    { day: 19, fact: "Mars has clouds and weather patterns similar to Earth." },
    { day: 20, fact: "Mars has a day length very similar to Earth's." },
    { day: 21, fact: "Mars has ancient volcanic activity that shaped its surface." },
    { day: 22, fact: "Mars has seasonal changes in its polar ice caps." },
    { day: 23, fact: "Mars has mineral deposits that suggest it once had liquid water." },
    { day: 24, fact: "Mars has a thin ozone layer in its atmosphere." },
    { day: 25, fact: "Mars experiences auroras, but they're different from Earth's." },
    { day: 26, fact: "Mars has been a target for future human exploration missions." },
    { day: 27, fact: "Mars has methane in its atmosphere, which could indicate life." },
    { day: 28, fact: "Mars has sand dunes that migrate across its surface." },
    { day: 29, fact: "Mars has a rusty appearance due to iron oxide in its soil." },
    { day: 30, fact: "Mars has layered rock formations that tell its geological history." },
    { day: 31, fact: "Mars is about half the size of Earth." }
  ],
  jupiter: [
    { day: 1, fact: "Jupiter is the largest planet in our solar system." },
    { day: 2, fact: "Jupiter has at least 95 known moons." },
    { day: 3, fact: "Jupiter's Great Red Spot is a storm larger than Earth." },
    { day: 4, fact: "Jupiter is a gas giant with no solid surface." },
    { day: 5, fact: "Jupiter has a strong magnetic field 20,000 times stronger than Earth's." },
    { day: 6, fact: "Jupiter acts as a 'cosmic vacuum cleaner' protecting inner planets." },
    { day: 7, fact: "A day on Jupiter lasts about 10 hours." },
    { day: 8, fact: "Jupiter takes 12 Earth years to orbit the Sun." },
    { day: 9, fact: "Jupiter has faint rings discovered in 1979." },
    { day: 10, fact: "Jupiter is made mostly of hydrogen and helium." },
    { day: 11, fact: "Jupiter's four largest moons are called the Galilean moons." },
    { day: 12, fact: "Jupiter's moon Europa may have an ocean beneath its icy surface." },
    { day: 13, fact: "Jupiter's moon Io has over 400 active volcanoes." },
    { day: 14, fact: "Jupiter's mass is greater than all other planets combined." },
    { day: 15, fact: "Jupiter emits more heat than it receives from the Sun." },
    { day: 16, fact: "Jupiter's atmosphere has wind speeds up to 400 km/h." },
    { day: 17, fact: "Jupiter has lightning strikes more powerful than Earth's." },
    { day: 18, fact: "Jupiter's core may be made of rock, metals, and hydrogen compounds." },
    { day: 19, fact: "Jupiter has been visited by nine spacecraft missions." },
    { day: 20, fact: "Jupiter's moon Ganymede is the largest moon in the solar system." },
    { day: 21, fact: "Jupiter is named after the king of Roman gods." },
    { day: 22, fact: "Jupiter's gravity affects the orbits of other planets." },
    { day: 23, fact: "Jupiter has auroras at its poles caused by its magnetic field." },
    { day: 24, fact: "Jupiter's atmosphere is divided into distinct bands and zones." },
    { day: 25, fact: "Jupiter could fit all other planets inside it with room to spare." },
    { day: 26, fact: "Jupiter's moon Callisto is the most heavily cratered body in the solar system." },
    { day: 27, fact: "Jupiter's rotation causes it to bulge at the equator." },
    { day: 28, fact: "Jupiter has at least 4 ring systems made of dust particles." },
    { day: 29, fact: "Jupiter's temperature at the core reaches about 20,000°C." },
    { day: 30, fact: "Jupiter's Great Red Spot has been observed for over 300 years." },
    { day: 31, fact: "Jupiter is visible to the naked eye and is often the fourth brightest object in the sky." }
  ],
  saturn: [
    { day: 1, fact: "Saturn is famous for its spectacular ring system." },
    { day: 2, fact: "Saturn has at least 146 known moons." },
    { day: 3, fact: "Saturn is the least dense planet and would float in water." },
    { day: 4, fact: "Saturn's largest moon, Titan, has a thick atmosphere." },
    { day: 5, fact: "Saturn takes 29.5 Earth years to orbit the Sun." },
    { day: 6, fact: "A day on Saturn lasts about 10.7 hours." },
    { day: 7, fact: "Saturn is the second largest planet in our solar system." },
    { day: 8, fact: "Saturn's rings are made of ice and rock particles." },
    { day: 9, fact: "Saturn has wind speeds up to 1,800 km/h." },
    { day: 10, fact: "Saturn is made mostly of hydrogen and helium like Jupiter." },
    { day: 11, fact: "Saturn's moon Enceladus has geysers of water ice." },
    { day: 12, fact: "Saturn has a hexagonal storm at its north pole." },
    { day: 13, fact: "Saturn's rings span up to 282,000 km in diameter." },
    { day: 14, fact: "Saturn has been visited by four spacecraft missions." },
    { day: 15, fact: "Saturn's magnetic field is nearly aligned with its rotation axis." },
    { day: 16, fact: "Saturn's moon Titan is larger than Mercury." },
    { day: 17, fact: "Saturn has seasonal changes that last about 7 Earth years each." },
    { day: 18, fact: "Saturn's rings are only about 10 meters thick on average." },
    { day: 19, fact: "Saturn is named after the Roman god of agriculture." },
    { day: 20, fact: "Saturn's gravity is similar to Earth's despite being much larger." },
    { day: 21, fact: "Saturn has auroras at both poles." },
    { day: 22, fact: "Saturn's moon Iapetus has a distinctive two-tone coloration." },
    { day: 23, fact: "Saturn's rings cast shadows on the planet's surface." },
    { day: 24, fact: "Saturn has shepherd moons that help maintain its ring structure." },
    { day: 25, fact: "Saturn emits 2.5 times more energy than it receives from the Sun." },
    { day: 26, fact: "Saturn's atmosphere contains ammonia ice crystals." },
    { day: 27, fact: "Saturn's moon Mimas has a large crater that makes it look like the Death Star." },
    { day: 28, fact: "Saturn's rings have gaps and divisions caused by gravitational forces." },
    { day: 29, fact: "Saturn's core temperature may reach 11,700°C." },
    { day: 30, fact: "Saturn's rings are constantly changing and evolving." },
    { day: 31, fact: "Saturn can be seen with the naked eye as a golden-colored star." }
  ],
  uranus: [
    { day: 1, fact: "Uranus rotates on its side with an 98-degree axial tilt." },
    { day: 2, fact: "Uranus has 27 known moons." },
    { day: 3, fact: "Uranus takes 84 Earth years to orbit the Sun." },
    { day: 4, fact: "A day on Uranus lasts about 17 hours." },
    { day: 5, fact: "Uranus is an ice giant made of water, methane, and ammonia." },
    { day: 6, fact: "Uranus has a faint ring system discovered in 1977." },
    { day: 7, fact: "Uranus is the coldest planet in our solar system." },
    { day: 8, fact: "Uranus has extreme seasons lasting 21 Earth years each." },
    { day: 9, fact: "Uranus has a blue-green color due to methane in its atmosphere." },
    { day: 10, fact: "Uranus was the first planet discovered with a telescope." },
    { day: 11, fact: "Uranus has the third-largest diameter of any planet." },
    { day: 12, fact: "Uranus has a weak magnetic field tilted 59 degrees from its axis." },
    { day: 13, fact: "Uranus has wind speeds up to 900 km/h." },
    { day: 14, fact: "Uranus is named after the Greek god of the sky." },
    { day: 15, fact: "Uranus has been visited by only one spacecraft, Voyager 2." },
    { day: 16, fact: "Uranus has clouds made of hydrogen sulfide." },
    { day: 17, fact: "Uranus has 13 known rings, much fainter than Saturn's." },
    { day: 18, fact: "Uranus experiences unusual aurora patterns due to its tilted magnetic field." },
    { day: 19, fact: "Uranus has a rocky core about the size of Earth." },
    { day: 20, fact: "Uranus's largest moons are Titania and Oberon." },
    { day: 21, fact: "Uranus has extreme temperature variations between its poles and equator." },
    { day: 22, fact: "Uranus may have been knocked on its side by a massive collision." },
    { day: 23, fact: "Uranus has atmospheric pressure about 1,000 times greater than Earth's at its core." },
    { day: 24, fact: "Uranus's moons are named after characters from Shakespeare and Pope." },
    { day: 25, fact: "Uranus has the most extreme seasons of any planet." },
    { day: 26, fact: "Uranus generates very little heat compared to other gas giants." },
    { day: 27, fact: "Uranus's unusual rotation may affect its magnetic field generation." },
    { day: 28, fact: "Uranus has lightning in its atmosphere." },
    { day: 29, fact: "Uranus's atmosphere is about 83% hydrogen and 15% helium." },
    { day: 30, fact: "Uranus has a very uniform temperature distribution." },
    { day: 31, fact: "Uranus is barely visible to the naked eye from Earth." }
  ],
  neptune: [
    { day: 1, fact: "Neptune is the windiest planet with speeds up to 2,100 km/h." },
    { day: 2, fact: "Neptune has 16 known moons." },
    { day: 3, fact: "Neptune takes 165 Earth years to orbit the Sun." },
    { day: 4, fact: "A day on Neptune lasts about 16 hours." },
    { day: 5, fact: "Neptune is the farthest planet from the Sun." },
    { day: 6, fact: "Neptune has a deep blue color due to methane in its atmosphere." },
    { day: 7, fact: "Neptune was the first planet discovered through mathematical prediction." },
    { day: 8, fact: "Neptune is an ice giant similar to Uranus." },
    { day: 9, fact: "Neptune has a strong magnetic field 27 times stronger than Earth's." },
    { day: 10, fact: "Neptune has 6 known rings named after astronomers." },
    { day: 11, fact: "Neptune's largest moon, Triton, orbits backwards." },
    { day: 12, fact: "Neptune has the Great Dark Spot, a storm system like Jupiter's." },
    { day: 13, fact: "Neptune is named after the Roman god of the sea." },
    { day: 14, fact: "Neptune has been visited by only one spacecraft, Voyager 2." },
    { day: 15, fact: "Neptune emits 2.6 times more energy than it receives from the Sun." },
    { day: 16, fact: "Neptune has clouds made of methane ice crystals." },
    { day: 17, fact: "Neptune's moon Triton has geysers of nitrogen." },
    { day: 18, fact: "Neptune has seasons that last about 40 Earth years each." },
    { day: 19, fact: "Neptune's core temperature reaches about 5,200°C." },
    { day: 20, fact: "Neptune has extreme weather patterns despite being far from the Sun." },
    { day: 21, fact: "Neptune's gravity is only 17% stronger than Earth's." },
    { day: 22, fact: "Neptune's rings are not uniform and have bright arcs." },
    { day: 23, fact: "Neptune has completed only one orbit since its discovery in 1846." },
    { day: 24, fact: "Neptune's moon Triton is gradually spiraling into the planet." },
    { day: 25, fact: "Neptune has auroras caused by its strong magnetic field." },
    { day: 26, fact: "Neptune's atmosphere is about 80% hydrogen and 19% helium." },
    { day: 27, fact: "Neptune has a rocky core about the size of Earth." },
    { day: 28, fact: "Neptune's winds are powered by internal heat rather than solar energy." },
    { day: 29, fact: "Neptune has the most dynamic and changing atmosphere of the gas giants." },
    { day: 30, fact: "Neptune cannot be seen with the naked eye from Earth." },
    { day: 31, fact: "Neptune's discovery confirmed Newton's law of universal gravitation." }
  ]
};

export function getFactForPlanet(planet: string, day: number): string | null {
  const planetKey = planet.toLowerCase();
  if (!(planetKey in planetaryFacts)) {
    return null;
  }
  
  const facts = planetaryFacts[planetKey];
  const fact = facts.find(f => f.day === day);
  
  return fact ? fact.fact : null;
}

export function getAllPlanets(): string[] {
  return Object.keys(planetaryFacts);
}
